"""Zero-config CLI wizard (Pillar 4): ``agentdiff init``.

Auto-detects the agent framework from installed packages and writes a
production-ready ``agentdiff.toml`` (v0.5 spec) plus a GitHub Actions
workflow, so a working gate exists in under 10 seconds.
"""

from __future__ import annotations

import importlib.util
from dataclasses import dataclass
from pathlib import Path

CONFIG_FILENAME = "agentdiff.toml"
WORKFLOW_PATH = Path(".github/workflows/agentdiff.yml")
APPROVE_WORKFLOW_PATH = Path(".github/workflows/agentdiff-approve.yml")

# Hosted identity service (Cloudflare Worker, stateless, free tier). Mints
# short-lived installation tokens for the project's AgentDiff App so the bot
# comments as agentdiff[bot] with zero per-repo configuration. Optional:
# workflows degrade to github-actions[bot] when the App isn't installed.
TOKEN_SERVICE_URL = "https://token.agentdiff.app"


@dataclass(frozen=True)
class FrameworkInfo:
    key: str
    label: str
    module: str
    adapter: str
    note: str


FRAMEWORKS: tuple[FrameworkInfo, ...] = (
    FrameworkInfo(
        key="langgraph",
        label="LangGraph",
        module="langgraph",
        adapter="langgraph",
        note="native LangGraph artifacts (state snapshots / checkpoints)",
    ),
    FrameworkInfo(
        key="crewai",
        label="CrewAI",
        module="crewai",
        adapter="crewai",
        note="CrewAI kickoff outputs",
    ),
    FrameworkInfo(
        key="openai_agents",
        label="OpenAI Agents SDK",
        module="agents",
        adapter="openai_agents",
        note="built-in SDK tracing (span_data exports)",
    ),
    FrameworkInfo(
        key="openinference",
        label="OpenTelemetry / OpenInference",
        module="openinference",
        adapter="openinference",
        note="OTel span exports (works for any instrumented framework)",
    ),
)

GENERIC = FrameworkInfo(
    key="generic",
    label="Generic / canonical",
    module="",
    adapter="generic",
    note="canonical AgentDiff traces (works everywhere)",
)


def detect_framework() -> FrameworkInfo:
    """Probes installed packages for a known agent framework."""
    for info in FRAMEWORKS:
        if importlib.util.find_spec(info.module) is not None:
            return info
    return GENERIC


TOML_TEMPLATE = """\
# AgentDiff configuration — generated by `agentdiff init`.
# Docs: https://github.com/kerrshift/agentdiff

[compare]
detect_loops = true
strict_tool_signatures = false

[adapter]
name = "{adapter}"

[invariants]
fail_on_identical_loops = true
# max_tool_repeats = 5   # hard cap per endpoint; uncomment to enable

[scenario.{scenario}]
mode = "statistical"
sample_runs = {runs}
max_cost_increase_pct = 20.0

[scenario.{scenario}.hard_invariants]
fail_on_identical_loops = true

[scenario.{scenario}.tolerances]
step_count_std_dev = 2.0
divergence_ceiling = 0.35
"""

WORKFLOW_TEMPLATE = """\
# AgentDiff CI gate — generated by `agentdiff init`.
# 1. EDIT the record target below (your agent callable).
# 2. Record a baseline envelope locally and commit it:
#      agentdiff record <your_agent:run> --runs {runs} --out {baseline}
# 3. Open a PR — this workflow diffs every run against it.

name: AgentDiff Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  agentdiff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install AgentDiff
        run: pip install agent-trajectory-diff

      - name: Record candidate trace
        run: |
          # EDIT ME: point this at your agent callable
          agentdiff record your_agent:run --input '{{{{"task": "demo"}}}}' \\
            --runs {runs} --out {candidate}

      - name: Gate against baseline envelope
        run: |
          agentdiff {candidate} \\
            --baseline {baseline} \\
            --fail-on-regression \\
            --scenario {scenario}

      - name: Upload candidate trace (for /agentdiff approve)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agentdiff-candidate-trace
          path: {candidate}
          retention-days: 7

      - name: Post PR report
        if: always()
        run: |
          agentdiff {candidate} \\
            --baseline {baseline} \\
            --format pr --pr ${{{{ github.event.number }}}} \\
            --scenario {scenario}
"""

APPROVE_WORKFLOW_TEMPLATE = """\
# AgentDiff Approve bot — generated by `agentdiff init --with-approve`.
# Reviewers comment `/agentdiff approve` on a PR to bless the candidate run
# as the new golden baseline. Loop violations are never blessable.
#
# Zero setup: works out of the box on the default GITHUB_TOKEN. The approve
# run verifies the gate itself and posts a green "AgentDiff Check" result on
# the new head via the Checks API (GITHUB_TOKEN pushes never re-trigger CI).
#
# Optional branding — comment/commit as agentdiff[bot] with the AgentDiff
# logo instead of github-actions[bot]: create a GitHub App named "AgentDiff"
# (or use the website's one-click installer) and upload
# .github/assets/agentdiff-avatar-512.png as its avatar:
#   Permissions: Contents RW, Pull requests RW, Issues comments RW, Actions R
#   Repo secrets: AGENTDIFF_APP_ID, AGENTDIFF_APP_PRIVATE_KEY
#   Repo variable: AGENTDIFF_APP_ID = <the app id>

name: AgentDiff Approve

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write

concurrency:
  group: agentdiff-approve-${{{{ github.event.issue.number }}}}
  cancel-in-progress: false

jobs:
  approve:
    if: >-
      ${{{{ github.event.issue.pull_request != null }}}}
      && startsWith(github.event.comment.body, '/agentdiff approve')
      && github.event.comment.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - name: Verify commenter has write access
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          PERM=$(gh api repos/${{{{ github.repository }}}}/collaborators/${{{{ github.event.comment.user.login }}}}/permission --jq .permission)
          if [ "$PERM" != "write" ] && [ "$PERM" != "admin" ]; then
            echo "Commenter ${{{{ github.event.comment.user.login }}}} lacks write access ($PERM). Refusing."
            gh pr comment ${{{{ github.event.issue.number }}}} --body "⛔ /agentdiff approve requires write access."
            exit 1
          fi

      - name: AgentDiff bot token (self-managed App, optional)
        id: app_token
        if: ${{{{ vars.AGENTDIFF_APP_ID != '' }}}}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{{{ secrets.AGENTDIFF_APP_ID }}}}
          private-key: ${{{{ secrets.AGENTDIFF_APP_PRIVATE_KEY }}}}

      - name: AgentDiff bot token (hosted service, zero config)
        id: minted_token
        if: ${{{{ steps.app_token.outputs.token == '' }}}}
        env:
          SERVICE_URL: {token_service}
          GH_TOKEN: ${{{{ github.token }}}}
          REPO: ${{{{ github.repository }}}}
        run: |
          # Mints a 1h agentdiff[bot] token when the AgentDiff App is
          # installed on this repo; prints nothing sensitive, stores nothing.
          RESP=$(curl -sS -X POST "$SERVICE_URL/token" \\
            -H "Content-Type: application/json" \\
            -d "{{\\"repository\\": \\"$REPO\\", \\"token\\": \\"$GH_TOKEN\\"}}" || true)
          BOT_TOKEN=$(echo "$RESP" | python3 -c 'import json,sys
          try: print(json.load(sys.stdin).get("token",""))
          except Exception: print("")' 2>/dev/null || true)
          if [ -n "$BOT_TOKEN" ]; then
            echo "token=$BOT_TOKEN" >> "$GITHUB_OUTPUT"
          fi

      - name: Select token
        id: token
        env:
          APP_TOKEN: ${{{{ steps.app_token.outputs.token }}}}
          MINTED: ${{{{ steps.minted_token.outputs.token }}}}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "token=$APP_TOKEN" >> "$GITHUB_OUTPUT"
          elif [ -n "$MINTED" ]; then
            echo "token=$MINTED" >> "$GITHUB_OUTPUT"
            echo "Branded agentdiff[bot] identity acquired via the AgentDiff App."
          else
            echo "token=${{{{ github.token }}}}" >> "$GITHUB_OUTPUT"
            echo "::notice::Using github-actions[bot] identity. Install the AgentDiff App (agentdiff install page or /apps/agentdiff) for the branded bot — everything else works identically."
          fi

      - name: Resolve PR head
        id: pr
        env:
          GH_TOKEN: ${{{{ steps.token.outputs.token }}}}
        run: |
          REF=$(gh pr view ${{{{ github.event.issue.number }}}} --json headRefName --jq .headRefName)
          echo "ref=$REF" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{{{ steps.pr.outputs.ref }}}}
          fetch-depth: 0
          token: ${{{{ steps.token.outputs.token }}}}

      - name: Find latest AgentDiff check run
        id: check
        env:
          GH_TOKEN: ${{{{ steps.token.outputs.token }}}}
        run: |
          RUN_ID=$(gh run list --workflow "AgentDiff Check" --branch "${{{{ steps.pr.outputs.ref }}}}" --limit 1 --json databaseId --jq '.[0].databaseId')
          echo "id=$RUN_ID" >> "$GITHUB_OUTPUT"

      - name: Download candidate trace
        uses: actions/download-artifact@v4
        with:
          name: agentdiff-candidate-trace
          path: traces/
          github-token: ${{{{ steps.token.outputs.token }}}}
          run-id: ${{{{ steps.check.outputs.id }}}}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install AgentDiff
        run: pip install agent-trajectory-diff

      - name: Re-baseline from the candidate run
        env:
          GH_TOKEN: ${{{{ steps.token.outputs.token }}}}
          AGENTDIFF_APPROVER: ${{{{ github.event.comment.user.login }}}}
        run: |
          agentdiff approve {baseline} {candidate} \\
            --scenario {scenario} --runs {runs} \\
            --pr ${{{{ github.event.issue.number }}}}

      - name: Commit the new baseline
        env:
          GH_TOKEN: ${{{{ steps.token.outputs.token }}}}
        run: |
          git config user.name "agentdiff[bot]"
          git config user.email "agentdiff[bot]@users.noreply.github.com"
          git add {baseline}
          git commit -m "chore(baseline): re-baseline via /agentdiff approve"
          git push origin HEAD:${{{{ steps.pr.outputs.ref }}}}

      - name: Post green AgentDiff Check on the new head
        env:
          GH_TOKEN: ${{{{ steps.token.outputs.token }}}}
        run: |
          SHA=$(git rev-parse HEAD)
          gh api repos/${{{{ github.repository }}}}/check-runs --input - <<JSON
          {{"name": "AgentDiff Check", "head_sha": "$SHA", "status": "completed", "conclusion": "success", "output": {{"title": "Re-baselined via /agentdiff approve", "summary": "The approve run verified the gate against the new baseline."}}}}
          JSON
"""


def _render_workflow(runs: int, scenario: str, baseline: str, candidate: str) -> str:
    return WORKFLOW_TEMPLATE.format(
        runs=runs, scenario=scenario, baseline=baseline, candidate=candidate
    )


def _render_approve_workflow(
    runs: int, scenario: str, baseline: str, candidate: str
) -> str:
    return APPROVE_WORKFLOW_TEMPLATE.format(
        runs=runs,
        scenario=scenario,
        baseline=baseline,
        candidate=candidate,
        token_service=TOKEN_SERVICE_URL,
    )


def write_config(
    directory: Path,
    *,
    framework: FrameworkInfo,
    scenario: str = "default",
    runs: int = 3,
    force: bool = False,
    with_approve: bool = False,
) -> list[Path]:
    """Writes ``agentdiff.toml`` + CI workflows. Returns created paths.

    Raises ``FileExistsError`` when a file already exists and ``force`` is
    not set — init is idempotent and never clobbers silently.

    ``with_approve`` also writes the ``/agentdiff approve`` bot workflow
    (Pillar 3).
    """
    directory.mkdir(parents=True, exist_ok=True)
    config_path = directory / CONFIG_FILENAME
    workflow_path = directory / WORKFLOW_PATH
    approve_path = directory / APPROVE_WORKFLOW_PATH

    created: list[Path] = []
    for path in (config_path, workflow_path, *([approve_path] if with_approve else [])):
        if path.exists() and not force:
            raise FileExistsError(f"{path} already exists (use --force to overwrite)")

    config_path.write_text(
        TOML_TEMPLATE.format(adapter=framework.adapter, scenario=scenario, runs=runs),
        encoding="utf-8",
    )
    created.append(config_path)

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    baseline = f"baselines/{scenario}.envelope.json"
    candidate = "traces/candidate.json"
    workflow_path.write_text(
        _render_workflow(
            runs=runs, scenario=scenario, baseline=baseline, candidate=candidate
        ),
        encoding="utf-8",
    )
    created.append(workflow_path)

    if with_approve:
        approve_path.write_text(
            _render_approve_workflow(
                runs=runs, scenario=scenario, baseline=baseline, candidate=candidate
            ),
            encoding="utf-8",
        )
        created.append(approve_path)
    return created
