"""Zero-config CLI wizard (Pillar 4): ``agentdiff init``.

Auto-detects the agent framework from installed packages and writes a
production-ready ``agentdiff.toml`` (v0.5 spec) plus a GitHub Actions
workflow, so a working gate exists in under 10 seconds.
"""

from __future__ import annotations

import importlib.util
from dataclasses import dataclass
from pathlib import Path

CONFIG_FILENAME = "agentdiff.toml"
WORKFLOW_PATH = Path(".github/workflows/agentdiff.yml")


@dataclass(frozen=True)
class FrameworkInfo:
    key: str
    label: str
    module: str
    adapter: str
    note: str


FRAMEWORKS: tuple[FrameworkInfo, ...] = (
    FrameworkInfo(
        key="langgraph",
        label="LangGraph",
        module="langgraph",
        adapter="langgraph",
        note="native LangGraph artifacts (state snapshots / checkpoints)",
    ),
    FrameworkInfo(
        key="crewai",
        label="CrewAI",
        module="crewai",
        adapter="crewai",
        note="CrewAI kickoff outputs",
    ),
    FrameworkInfo(
        key="openai_agents",
        label="OpenAI Agents SDK",
        module="agents",
        adapter="openai_agents",
        note="built-in SDK tracing (span_data exports)",
    ),
    FrameworkInfo(
        key="openinference",
        label="OpenTelemetry / OpenInference",
        module="openinference",
        adapter="openinference",
        note="OTel span exports (works for any instrumented framework)",
    ),
)

GENERIC = FrameworkInfo(
    key="generic",
    label="Generic / canonical",
    module="",
    adapter="generic",
    note="canonical AgentDiff traces (works everywhere)",
)


def detect_framework() -> FrameworkInfo:
    """Probes installed packages for a known agent framework."""
    for info in FRAMEWORKS:
        if importlib.util.find_spec(info.module) is not None:
            return info
    return GENERIC


TOML_TEMPLATE = """\
# AgentDiff configuration — generated by `agentdiff init`.
# Docs: https://github.com/lostmartian/agentdiff

[compare]
detect_loops = true
strict_tool_signatures = false

[adapter]
name = "{adapter}"

[invariants]
fail_on_identical_loops = true
# max_tool_repeats = 5   # hard cap per endpoint; uncomment to enable

[scenario.{scenario}]
mode = "statistical"
sample_runs = {runs}
max_cost_increase_pct = 20.0

[scenario.{scenario}.hard_invariants]
fail_on_identical_loops = true

[scenario.{scenario}.tolerances]
step_count_std_dev = 2.0
divergence_ceiling = 0.35
"""

WORKFLOW_TEMPLATE = """\
# AgentDiff CI gate — generated by `agentdiff init`.
# 1. EDIT the record target below (your agent callable).
# 2. Record a baseline envelope locally and commit it:
#      agentdiff record <your_agent:run> --runs {runs} --out {baseline}
# 3. Open a PR — this workflow diffs every run against it.

name: AgentDiff Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  agentdiff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install AgentDiff
        run: pip install agent-trajectory-diff

      - name: Record candidate trace
        run: |
          # EDIT ME: point this at your agent callable
          agentdiff record your_agent:run --input '{{{{"task": "demo"}}}}' \\
            --runs {runs} --out {candidate}

      - name: Gate against baseline envelope
        run: |
          agentdiff {candidate} \\
            --baseline {baseline} \\
            --fail-on-regression \\
            --scenario {scenario}

      - name: Post PR report
        if: always()
        run: |
          agentdiff {candidate} \\
            --baseline {baseline} \\
            --format pr --pr ${{{{ github.event.number }}}} \\
            --scenario {scenario}
"""


def _render_workflow(runs: int, scenario: str, baseline: str, candidate: str) -> str:
    return WORKFLOW_TEMPLATE.format(
        runs=runs, scenario=scenario, baseline=baseline, candidate=candidate
    )


def write_config(
    directory: Path,
    *,
    framework: FrameworkInfo,
    scenario: str = "default",
    runs: int = 3,
    force: bool = False,
) -> list[Path]:
    """Writes ``agentdiff.toml`` + the CI workflow. Returns created paths.

    Raises ``FileExistsError`` when a file already exists and ``force`` is
    not set — init is idempotent and never clobbers silently.
    """
    directory.mkdir(parents=True, exist_ok=True)
    config_path = directory / CONFIG_FILENAME
    workflow_path = directory / WORKFLOW_PATH

    created: list[Path] = []
    if config_path.exists() and not force:
        raise FileExistsError(
            f"{config_path} already exists (use --force to overwrite)"
        )
    if workflow_path.exists() and not force:
        raise FileExistsError(
            f"{workflow_path} already exists (use --force to overwrite)"
        )

    config_path.write_text(
        TOML_TEMPLATE.format(adapter=framework.adapter, scenario=scenario, runs=runs),
        encoding="utf-8",
    )
    created.append(config_path)

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    baseline = f"baselines/{scenario}.envelope.json"
    candidate = "traces/candidate.json"
    workflow_path.write_text(
        _render_workflow(
            runs=runs, scenario=scenario, baseline=baseline, candidate=candidate
        ),
        encoding="utf-8",
    )
    created.append(workflow_path)
    return created
