import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Copy, ExternalLink, GitPullRequest, RotateCcw, ShieldCheck, Terminal, AlertTriangle, PlayCircle } from "lucide-react";
import Reveal from "@/components/Reveal";
import CodeBlock from "@/components/CodeBlock";

const SITE_URL = "https://agentdiff.app";

export const metadata: Metadata = {
  title: "GitHub Action — Automated Agent Trajectory Regression Gate",
  description:
    "Block agent trajectory regressions in CI on every PR. Automated diffing against golden baselines, real-time PR comments, root cause blame trees, and Goodhart threshold protection.",
  keywords: [
    "agentdiff-check GitHub Action",
    "CI/CD agent testing",
    "PR trajectory check",
    "automated regression gate",
    "GitHub Actions AI testing",
  ],
  authors: [{ name: "AgentDiff", url: SITE_URL }],
  creator: "AgentDiff",
  publisher: "AgentDiff",
  alternates: { canonical: "/action" },
  robots: { index: true, follow: true },
  openGraph: {
    title: "GitHub Action | AgentDiff",
    description:
      "Block agent trajectory regressions in CI on every PR with automated PR commentary, threshold governance, and baseline rotation.",
    url: `${SITE_URL}/action`,
    siteName: "AgentDiff",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "GitHub Action | AgentDiff",
    description:
      "Block agent trajectory regressions in CI on every PR with automated PR commentary, threshold governance, and baseline rotation.",
  },
};

const ACTION_INPUTS = [
  {
    name: "baseline",
    req: true,
    desc: "Path to the committed golden baseline trace JSON in your repository.",
  },
  {
    name: "candidate",
    req: true,
    desc: "Path to the candidate trace JSON generated by the agent during the current PR workflow run.",
  },
  {
    name: "pr",
    req: false,
    desc: "Pull request number (e.g. ${{ github.event.number }}) to post the formatted divergence report and culprit blame tree to.",
  },
  {
    name: "baseline-config",
    req: false,
    desc: "Path to the main branch agentdiff.toml. Enables the Goodhart guard to detect if PR authors silently weakened tolerance thresholds.",
  },
  {
    name: "adapter",
    req: false,
    desc: "Telemetry parser: auto (default), langgraph, crewai, openai_agents, openinference, langfuse, langsmith, generic.",
  },
  {
    name: "update-baseline",
    req: false,
    desc: "When true, automatically advances the stored golden baseline trace if the PR trajectory verdict passes all quality gates.",
  },
  {
    name: "github-token",
    req: false,
    desc: "GitHub secret token (e.g. ${{ secrets.GITHUB_TOKEN }}) with pull-requests: write permission for automated commentary.",
  },
];

export default function ActionPage() {
  return (
    <div className="w-full font-sans divide-y divide-(--border)">
      
      {/* 1. MARKETING HERO */}
      <section className="relative overflow-hidden pt-20 pb-20 sm:pt-24 sm:pb-28 bg-transparent w-full">
        {/* Subtle top spotlight glow */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-5xl h-[300px] bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-emerald-500/15 via-emerald-500/5 to-transparent blur-3xl pointer-events-none -z-10" />

        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <Reveal>
            <div className="max-w-4xl">
              <span className="text-xs uppercase tracking-[0.18em] text-(--faint) block mb-4 font-medium">
                Official GitHub Action
              </span>
              <h1 className="text-3xl sm:text-5xl lg:text-6xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.08]">
                Gate AI agent regressions <span className="text-emerald-500/90 dark:text-emerald-400">on every pull request.</span>
              </h1>
              <p className="mt-6 text-base sm:text-lg lg:text-xl text-(--muted) leading-relaxed max-w-3xl font-normal">
                Drop <code className="text-xs sm:text-sm font-mono text-(--fg) bg-(--surface-2) px-2 py-0.5 rounded border border-(--border)">agentdiff-check</code> into your CI pipeline. Diff candidate execution graphs against golden baselines, post rich diagnostic blame trees to PR comments, and lock the merge button if thresholds fail.
              </p>

              {/* High-Impact Proof Points */}
              <div className="mt-8 flex flex-wrap items-center gap-6 text-xs text-(--muted)">
                <span className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                  <span className="text-(--fg) font-semibold">30-Second Setup with agentdiff init</span>
                </span>
                <span className="text-(--border) select-none">•</span>
                <span className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                  <span>Interactive /agentdiff approve Bot</span>
                </span>
                <span className="text-(--border) select-none">•</span>
                <span className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                  <span>Hosted Identity (agentdiff[bot])</span>
                </span>
              </div>

              <div className="mt-8 flex flex-wrap items-center gap-4">
                <a
                  href="https://github.com/apps/agentdiff-ci"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-6 py-3 rounded-full bg-(--fg) text-(--bg) text-xs font-semibold hover:opacity-90 transition-opacity inline-flex items-center gap-2 shadow-sm"
                >
                  <span>Install GitHub App</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </a>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* 2. PRODUCTION WORKFLOW SPECIFICATION (SIDE-BY-SIDE BLUEPRINT) */}
      <section className="py-24 sm:py-32 w-full bg-transparent">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-start">
            
            {/* Left Column: Workflow Narrative */}
            <div className="lg:col-span-5 space-y-5">
              <span className="text-xs uppercase tracking-[0.18em] text-(--faint) font-medium block">
                01 / CI Integration
              </span>
              <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.1]">
                Drop into any repo in 30 seconds.
              </h2>
              <p className="text-base text-(--muted) leading-relaxed font-normal">
                Generate your gate in one command with <code className="text-xs font-mono text-(--fg) bg-(--surface-2) px-1.5 py-0.5 rounded border border-(--border)">agentdiff init --with-approve</code>. If divergence, cost, or retry loops breach tolerance, the action fails with exit code 1 and posts a human-first PR verdict.
              </p>

              <div className="pt-2">
                <a
                  href="https://github.com/lostmartian/agentdiff-demo/pull/4"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-xs sm:text-sm font-semibold text-emerald-500 hover:underline"
                >
                  <span>Inspect live PR comment demo on GitHub #4</span>
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </div>

            {/* Right Column: Workflow Yaml */}
            <div className="lg:col-span-7">
              <div className="rounded-2xl border border-(--border) bg-(--surface) overflow-hidden shadow-2xs">
                <CodeBlock
                  language="yaml"
                  filename=".github/workflows/agentdiff.yml"
                  code={`name: AgentDiff Gate
on: [pull_request]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Record Candidate Trace
        run: |
          pip install agent-trajectory-diff
          agentdiff record my_agent:run \\
            --input '{"scenario": "customer_support"}' \\
            --output traces/pr_candidate.json

      - name: Gate Against Statistical Baseline Envelope
        uses: kerrshift/agentdiff/.github/actions/agentdiff-check@v0.5.0
        with:
          baseline: baselines/customer_support.envelope.json
          candidate: traces/pr_candidate.json
          pr: \${{ github.event.number }}
          github-token: \${{ secrets.GITHUB_TOKEN }}`}
                />
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* 3. THREE AUTOMATION DELIVERABLES */}
      <section className="py-24 sm:py-32 w-full bg-transparent">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <Reveal>
            <div className="max-w-3xl mb-16 sm:mb-20">
              <span className="text-xs uppercase tracking-[0.18em] text-(--faint) block mb-3 font-medium">
                02 / Core Deliverables
              </span>
              <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.1]">
                What happens on every pull request.
              </h2>
              <p className="mt-4 text-base sm:text-lg text-(--muted) leading-relaxed font-normal">
                Three deterministic safeguards run on every push, giving your team actionable feedback before bad code hits main.
              </p>
            </div>
          </Reveal>

          {/* 3 Value Pillars: High-Converting Open Layout */}
          <Reveal delay={100}>
            <div className="border-t border-(--border)">
              <div className="grid grid-cols-1 lg:grid-cols-3 divide-y lg:divide-y-0 lg:divide-x divide-(--border)">
                
                {/* Pillar 1: Rich PR Commentary */}
                <div className="py-10 lg:py-12 lg:pr-10 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs uppercase tracking-wider text-emerald-500 font-semibold">
                      Deliverable 01
                    </span>
                    <GitPullRequest className="w-4 h-4 text-emerald-400" />
                  </div>
                  <h3 className="text-xl font-bold text-(--fg) tracking-tight">
                    Rich PR Diagnostic Commentary
                  </h3>
                  <p className="text-sm sm:text-base text-(--muted) leading-relaxed">
                    Posts an interactive markdown summary directly to the PR with exact divergence ratios, step-by-step diff trees, token spikes, and isolated culprit root-cause lines.
                  </p>
                  <div className="pt-2 flex items-center gap-2 text-xs text-(--muted)">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                    <span>Instant team visibility without log parsing</span>
                  </div>
                </div>

                {/* Pillar 2: Exit Code 1 Enforcement */}
                <div className="py-10 lg:py-12 lg:px-10 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs uppercase tracking-wider text-rose-500 font-semibold">
                      Deliverable 02
                    </span>
                    <ShieldCheck className="w-4 h-4 text-rose-500" />
                  </div>
                  <h3 className="text-xl font-bold text-(--fg) tracking-tight">
                    Exit Code 1 Merge Blocker
                  </h3>
                  <p className="text-sm sm:text-base text-(--muted) leading-relaxed">
                    Emits strict non-zero exit codes upon regression, automatically failing the GitHub check suite and preventing engineers from merging broken agent behaviors.
                  </p>
                  <div className="pt-2 flex items-center gap-2 text-xs text-(--muted)">
                    <span className="w-1.5 h-1.5 rounded-full bg-rose-500" />
                    <span>100% Deterministic branch protection</span>
                  </div>
                </div>

                {/* Pillar 3: Interactive Approve Bot & Baseline Rotation */}
                <div className="py-10 lg:py-12 lg:pl-10 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs uppercase tracking-wider text-emerald-500 font-semibold">
                      Deliverable 03
                    </span>
                    <RotateCcw className="w-4 h-4 text-emerald-400" />
                  </div>
                  <h3 className="text-xl font-bold text-(--fg) tracking-tight">
                    Interactive /agentdiff approve Bot
                  </h3>
                  <p className="text-sm sm:text-base text-(--muted) leading-relaxed">
                    Reviewers bless intentional improvements directly by commenting <code className="text-xs font-mono text-(--fg) bg-(--surface-2) px-1.5 py-0.5 rounded border border-(--border)">/agentdiff approve</code>. Candidate runs join the baseline envelope without local checkouts or manual JSON edits.
                  </p>
                  <div className="pt-2 flex items-center gap-2 text-xs text-(--muted)">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                    <span>Hosted identity as agentdiff[bot] via token.agentdiff.app</span>
                  </div>
                </div>

              </div>
            </div>
          </Reveal>

          {/* Approve Bot Spotlight Box */}
          <Reveal delay={120}>
            <div className="mt-16 p-8 sm:p-10 rounded-3xl border border-(--border) bg-(--surface) shadow-2xs space-y-6">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="space-y-1">
                  <span className="text-xs uppercase tracking-wider text-emerald-500 font-semibold">
                    In-PR Workflow
                  </span>
                  <h3 className="text-2xl font-bold text-(--fg) tracking-tight">
                    Bless improvements without leaving GitHub
                  </h3>
                </div>
                <a
                  href="https://github.com/apps/agentdiff-ci"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-5 py-2 rounded-full bg-(--fg) text-(--bg) text-xs font-semibold hover:opacity-90 transition-opacity inline-flex items-center gap-2"
                >
                  <span>Install AgentDiff CI App</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </a>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-xs text-(--muted) divide-y md:divide-y-0 md:divide-x divide-(--border)">
                <div className="space-y-2 md:pr-6">
                  <div className="font-semibold text-(--fg) text-sm">1. Reviewer Comment</div>
                  <p className="leading-relaxed">
                    A team member with write access comments <code className="text-xs font-mono text-(--fg) bg-(--surface-2) px-1 rounded">/agentdiff approve</code> on a PR flagged for path drift.
                  </p>
                </div>
                <div className="space-y-2 md:px-6 pt-4 md:pt-0">
                  <div className="font-semibold text-(--fg) text-sm">2. D3 Invariant Check</div>
                  <p className="leading-relaxed">
                    Path drift and cost deltas are blessable; infinite loops are <strong>never blessable</strong>. The bot refuses to bless cyclical bugs.
                  </p>
                </div>
                <div className="space-y-2 md:pl-6 pt-4 md:pt-0">
                  <div className="font-semibold text-(--fg) text-sm">3. Green Checks-API Flip</div>
                  <p className="leading-relaxed">
                    The bot updates the committed baseline envelope, pushes the commit, and flips the GitHub Check result to green.
                  </p>
                </div>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* 4. GOODHART THRESHOLD GUARD */}
      <section className="py-24 sm:py-32 w-full bg-transparent">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-start">
            
            {/* Left Column: Explanation */}
            <div className="lg:col-span-5 space-y-5">
              <span className="text-xs uppercase tracking-[0.18em] text-amber-500 font-medium block">
                03 / Governance &amp; Security
              </span>
              <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.1]">
                Did the PR pass — or did the gate move?
              </h2>
              <p className="text-base text-(--muted) leading-relaxed font-normal">
                When developers weaken test thresholds (e.g. raising <code className="text-xs font-mono text-(--fg) bg-(--surface-2) px-1.5 py-0.5 rounded border border-(--border)">max_divergence</code> from 0.25 to 0.75 to force a broken agent to pass), AgentDiff compares the PR configuration against the main branch baseline config.
              </p>

              <div className="p-4 rounded-xl bg-(--surface-2)/60 border border-(--border) space-y-2">
                <div className="flex items-center gap-2 text-xs font-semibold text-amber-500 dark:text-amber-400">
                  <AlertTriangle className="w-4 h-4" />
                  <span>Goodhart&apos;s Law Protection Active</span>
                </div>
                <p className="text-xs text-(--muted) leading-relaxed">
                  Threshold alterations are flagged as high-priority security warnings in the PR review timeline, preventing silent regression masking.
                </p>
              </div>
            </div>

            {/* Right Column: Governance Yaml */}
            <div className="lg:col-span-7">
              <div className="rounded-2xl border border-(--border) bg-(--surface) overflow-hidden shadow-2xs">
                <CodeBlock
                  language="yaml"
                  filename="governance_step.yml"
                  code={`      - name: Fetch Baseline Policy from Main
        run: git show origin/main:agentdiff.toml > /tmp/baseline-agentdiff.toml

      - name: Gate Against Baseline with Governance Guard
        uses: kerrshift/agentdiff/.github/actions/agentdiff-check@v0.5.0
        with:
          baseline: baselines/golden_run.json
          candidate: traces/pr_candidate.json
          baseline-config: /tmp/baseline-agentdiff.toml # Flags loosened thresholds
          pr: \${{ github.event.number }}
          github-token: \${{ secrets.GITHUB_TOKEN }}`}
                />
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* 5. COMPLETE ACTION INPUTS SPECIFICATION */}
      <section className="py-24 sm:py-32 w-full bg-transparent">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <Reveal>
            <div className="max-w-3xl mb-16 sm:mb-20">
              <span className="text-xs uppercase tracking-[0.18em] text-(--faint) block mb-3 font-medium">
                04 / Parameters &amp; Config
              </span>
              <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.1]">
                Complete Action inputs specification.
              </h2>
              <p className="mt-4 text-base sm:text-lg text-(--muted) leading-relaxed font-normal">
                Everything configurable in <code className="text-xs font-mono text-(--fg) bg-(--surface-2) px-1.5 py-0.5 rounded border border-(--border)">agentdiff-check</code>:
              </p>
            </div>
          </Reveal>

          <Reveal delay={100}>
            <div className="rounded-2xl border border-(--border) bg-(--surface) overflow-hidden shadow-2xs">
              <div className="overflow-x-auto">
                <table className="w-full text-sm border-collapse min-w-[700px]">
                  <thead>
                    <tr className="border-b border-(--border) bg-(--surface-2)/60 text-(--muted) text-left font-medium text-xs">
                      <th className="py-3.5 px-5 w-4/12">Parameter</th>
                      <th className="py-3.5 px-5 w-2/12">Requirement</th>
                      <th className="py-3.5 px-5 w-6/12">Description</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-(--border) text-(--muted)">
                    {ACTION_INPUTS.map((input) => (
                      <tr key={input.name} className="hover:bg-(--surface-2)/30 transition-colors">
                        <td className="py-4 px-5 font-mono text-xs font-semibold text-(--fg)">
                          {input.name}
                        </td>
                        <td className="py-4 px-5">
                          {input.req ? (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold bg-emerald-500/10 text-emerald-500 border border-emerald-500/20">
                              Required
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-normal text-(--faint) bg-(--surface-2) border border-(--border)">
                              Optional
                            </span>
                          )}
                        </td>
                        <td className="py-4 px-5 text-sm text-(--muted) leading-relaxed">
                          {input.desc}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* 6. CTA BANNER */}
      <section className="py-24 sm:py-36 w-full bg-transparent text-center border-t border-(--border) relative overflow-hidden">
        {/* Top-Right Emerald Flare */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-emerald-500/15 dark:bg-emerald-400/20 rounded-full blur-[100px] pointer-events-none -mr-20 -mt-20" />
        
        {/* Center ambient wash */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-4xl h-[300px] bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <Reveal>
            <div className="max-w-3xl mx-auto space-y-6">
              <span className="text-xs uppercase tracking-[0.18em] text-(--faint) block font-medium">
                Continuous Protection
              </span>
              <h2 className="text-3xl sm:text-5xl lg:text-6xl font-bold tracking-[-0.035em] text-(--fg) leading-[1.08]">
                Record. Diff. Gate. <span className="text-emerald-500/90 dark:text-emerald-400">Ship with confidence.</span>
              </h2>
              <p className="text-base sm:text-lg text-(--muted) max-w-xl mx-auto font-normal leading-relaxed">
                Add one GitHub Action step to automate trajectory regression testing across your engineering team in under 5 minutes.
              </p>
              <div className="flex flex-wrap items-center justify-center gap-4 pt-4 text-sm font-semibold">
                <a
                  href="https://github.com/apps/agentdiff-ci"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-8 py-3.5 rounded-full bg-(--fg) text-(--bg) hover:opacity-90 transition-opacity shadow-sm"
                >
                  Install GitHub App →
                </a>
                <Link
                  href="/quickstart"
                  className="px-8 py-3.5 rounded-full border border-(--border) text-(--fg) hover:bg-(--surface-2) transition-colors"
                >
                  Quickstart Guide
                </Link>
                <Link
                  href="/docs"
                  className="px-8 py-3.5 rounded-full border border-(--border) text-(--fg) hover:bg-(--surface-2) transition-colors"
                >
                  Explore Full CLI Docs
                </Link>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

    </div>
  );
}
