import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, GitPullRequest, ShieldCheck, ShieldAlert, Sparkles, Terminal, FileCode2, ExternalLink, RotateCcw, AlertTriangle } from "lucide-react";
import Reveal from "@/components/Reveal";
import CodeBlock from "@/components/CodeBlock";

const SITE_URL = "https://agentdiff.lostmartian.in";

export const metadata: Metadata = {
  title: "GitHub Action — Automated Trajectory Regression Gate",
  description:
    "Gate AI agent regressions on every pull request with the official agentdiff-check GitHub Action. Real-time PR commentary, threshold governance, and automated baseline rotation.",
  keywords: [
    "agentdiff-check GitHub Action",
    "CI/CD agent testing",
    "PR trajectory check",
    "automated regression gate",
    "GitHub Actions AI testing",
  ],
  authors: [{ name: "AgentDiff", url: SITE_URL }],
  creator: "AgentDiff",
  publisher: "AgentDiff",
  alternates: { canonical: "/action" },
  robots: { index: true, follow: true },
  openGraph: {
    title: "GitHub Action | AgentDiff",
    description:
      "Gate AI agent regressions on every pull request with agentdiff-check — automated PR commentary, threshold governance, and baseline rotation.",
    url: `${SITE_URL}/action`,
    siteName: "AgentDiff",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "GitHub Action | AgentDiff",
    description:
      "Gate AI agent regressions on every pull request with agentdiff-check — automated PR commentary, threshold governance, and baseline rotation.",
  },
};

const ACTION_INPUTS = [
  {
    name: "baseline",
    req: true,
    desc: "Path to the committed golden baseline trace JSON. When update-baseline is active, establishing this on clean runs is automatic.",
  },
  {
    name: "candidate",
    req: true,
    desc: "Path to the candidate trace JSON generated by the agent during the current PR workflow run.",
  },
  {
    name: "pr",
    req: false,
    desc: "Pull request number (e.g. ${{ github.event.number }}) to post the formatted divergence report and culprit explanation to.",
  },
  {
    name: "baseline-config",
    req: false,
    desc: "Path to the baseline's agentdiff.toml. Enables the Goodhart guard to detect if PR authors silently loosened test thresholds.",
  },
  {
    name: "adapter",
    req: false,
    desc: "Telemetry parser adapter: auto (default), generic, openinference, langfuse, langsmith, openai_agents, langgraph, crewai.",
  },
  {
    name: "update-baseline",
    req: false,
    desc: "Set to true to automatically advance the golden baseline trace when the PR verdict is completely clean.",
  },
  {
    name: "max-divergence / max-cost-delta / max-loops",
    req: false,
    desc: "Explicit override thresholds for TDI divergence [0.0-1.0], max cost delta percentage, and loop count allowances.",
  },
];

export default function ActionPage() {
  return (
    <div className="w-full font-sans pb-32">
      {/* 1. MARKETING HERO */}
      <section className="pt-24 pb-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <Reveal>
          <div className="max-w-5xl">
            <span className="text-xs font-mono uppercase tracking-[0.18em] text-(--faint) block mb-4">
              Continuous Integration
            </span>
            <h1
              className="font-semibold tracking-[-0.035em] text-(--fg) leading-[1.04]"
              style={{ fontSize: "var(--text-display)" }}
            >
              Gate agent regressions on every PR.
            </h1>
            <p
              className="mt-6 text-base sm:text-lg text-(--muted) leading-relaxed max-w-4xl font-normal"
              style={{ lineHeight: "var(--leading-subtitle)" }}
            >
              The <code className="font-mono text-xs text-(--fg) bg-(--surface-2) px-1.5 py-0.5 rounded border border-(--border)">agentdiff-check</code> GitHub Action diffs candidate agent trajectories against your committed golden baselines, posts an interactive diagnostic report directly to the PR, and blocks the merge if regressions occur.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-6 text-sm font-mono">
              <span className="text-(--fg) font-semibold">1-Step Action Workflow</span>
              <span className="text-(--border-strong)">•</span>
              <span className="text-(--muted)">Automated PR Comment Verdicts</span>
              <span className="text-(--border-strong)">•</span>
              <span className="text-(--muted)">Goodhart Threshold Guard</span>
            </div>
          </div>
        </Reveal>
      </section>

      {/* 2. THE PRODUCTION WORKFLOW SPECIFICATION */}
      <section className="py-12 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-start">
          {/* Left Column: Context */}
          <div className="lg:col-span-5 space-y-4">
            <div className="flex items-center gap-3">
              <span className="text-xs font-mono font-bold text-emerald-500 px-2.5 py-1 rounded bg-emerald-500/10 border border-emerald-500/25">
                01
              </span>
              <span className="text-xs font-mono uppercase tracking-wider text-(--faint)">
                GITHUB ACTION WORKFLOW
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-(--fg)">
              Drop into Any Repository in 30 Seconds
            </h2>
            <p className="text-sm sm:text-base text-(--muted) leading-relaxed">
              Execute your agent in CI, record a PR candidate trace, and invoke <code className="font-mono text-xs text-(--fg)">agentdiff-check</code>. If divergence or loop thresholds are breached, the action exits with code 1 and blocks the merge button.
            </p>
            <div className="pt-2">
              <a
                href="https://github.com/lostmartian/agentdiff-demo/pull/3"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-xs font-mono font-semibold text-(--fg) hover:text-(--accent) transition-colors"
              >
                <span>Inspect Live Demo on GitHub PR #3</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
          </div>

          {/* Right Column: Workflow Yaml */}
          <div className="lg:col-span-7">
            <CodeBlock
              language="yaml"
              filename=".github/workflows/agentdiff.yml"
              code={`name: AgentDiff Gate
on: [pull_request]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Record Candidate Trace
        run: |
          pip install agent-trajectory-diff
          agentdiff record my_agent:run \\
            --input '{"scenario": "checkout"}' \\
            --output traces/pr_candidate.json

      - name: Gate Against Golden Baseline
        uses: lostmartian/agentdiff/.github/actions/agentdiff-check@main
        with:
          baseline: baselines/golden_run.json
          candidate: traces/pr_candidate.json
          pr: \${{ github.event.number }}
          github-token: \${{ secrets.GITHUB_TOKEN }}`}
            />
          </div>
        </div>
      </section>

      {/* 3. THREE CORE ARTIFACTS ON EVERY PR */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 border-t border-(--border)">
        <Reveal>
          <div className="mb-14 max-w-3xl">
            <span className="text-xs font-mono uppercase tracking-[0.18em] text-(--faint) block mb-2">
              Automation Deliverables
            </span>
            <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-(--fg)">
              What Happens on Every PR Commit
            </h2>
            <p className="mt-3 text-sm sm:text-base text-(--muted) leading-relaxed">
              Three deterministic safeguards are deployed automatically on every pull request:
            </p>
          </div>
        </Reveal>

        <Reveal delay={100}>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="p-7 rounded-3xl bg-(--surface-2)/40 border border-(--border) space-y-4">
              <div className="w-11 h-11 rounded-2xl bg-(--surface) border border-(--border) flex items-center justify-center text-(--fg)">
                <GitPullRequest className="w-5 h-5 text-(--accent)" />
              </div>
              <div>
                <div className="text-[11px] font-mono uppercase tracking-wider text-(--faint)">DIAGNOSTIC COMMENT</div>
                <h3 className="text-lg font-semibold text-(--fg) mt-1">Rich PR Commentary</h3>
              </div>
              <p className="text-sm text-(--muted) leading-relaxed">
                Posts a complete regression breakdown table, topological diff trees, cost percentage changes, and the exact culprit step directly into the PR review timeline.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="p-7 rounded-3xl bg-(--surface-2)/20 border border-(--border) space-y-4">
              <div className="w-11 h-11 rounded-2xl bg-(--surface) border border-(--border) flex items-center justify-center text-(--fg)">
                <ShieldCheck className="w-5 h-5 text-emerald-500" />
              </div>
              <div>
                <div className="text-[11px] font-mono uppercase tracking-wider text-(--faint)">STRICT CI ENFORCEMENT</div>
                <h3 className="text-lg font-semibold text-(--fg) mt-1">Exit Code 1 Merge Blocker</h3>
              </div>
              <p className="text-sm text-(--muted) leading-relaxed">
                <code className="font-mono text-xs text-(--fg)">--fail-on-regression</code> causes the GitHub Action step to exit with code 1 upon threshold violations, keeping GitHub&apos;s merge button locked.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="p-7 rounded-3xl bg-(--surface-2)/20 border border-(--border) space-y-4">
              <div className="w-11 h-11 rounded-2xl bg-(--surface) border border-(--border) flex items-center justify-center text-(--fg)">
                <RotateCcw className="w-5 h-5 text-blue-500" />
              </div>
              <div>
                <div className="text-[11px] font-mono uppercase tracking-wider text-(--faint)">AUTOMATED ROTATION</div>
                <h3 className="text-lg font-semibold text-(--fg) mt-1">Clean Baseline Rotation</h3>
              </div>
              <p className="text-sm text-(--muted) leading-relaxed">
                Pass <code className="font-mono text-xs text-(--fg)">update-baseline: true</code> to advance the stored golden baseline only when candidate runs pass all mathematical regression criteria.
              </p>
            </div>
          </div>
        </Reveal>
      </section>

      {/* 4. THE GOODHART THRESHOLD GUARD */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 border-t border-(--border)">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-start">
          {/* Left Column: Explanation */}
          <div className="lg:col-span-5 space-y-4">
            <div className="flex items-center gap-3">
              <span className="text-xs font-mono font-bold text-amber-500 px-2.5 py-1 rounded bg-amber-500/10 border border-amber-500/25">
                02
              </span>
              <span className="text-xs font-mono uppercase tracking-wider text-(--faint)">
                THRESHOLD GOVERNANCE
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-(--fg)">
              Did the PR Pass — or Did the Gate Move?
            </h2>
            <p className="text-sm sm:text-base text-(--muted) leading-relaxed">
              When developers weaken test thresholds (e.g. raising <code className="font-mono text-xs text-(--fg)">max_divergence</code> from 0.25 to 0.70 to force a broken PR to pass), AgentDiff compares the PR configuration against the main branch baseline config.
            </p>
            <div className="p-4 rounded-xl bg-(--surface-2)/40 border border-(--border) space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono font-semibold text-amber-500 dark:text-amber-400">
                <AlertTriangle className="w-3.5 h-3.5" />
                <span>Goodhart&apos;s Law Protection</span>
              </div>
              <p className="text-xs text-(--muted) leading-relaxed">
                Threshold alterations are surfaced as explicit security warnings in the PR verdict, making test weakening immediately visible to code reviewers.
              </p>
            </div>
          </div>

          {/* Right Column: Governance Snippet */}
          <div className="lg:col-span-7">
            <CodeBlock
              language="yaml"
              filename="governance_step.yml"
              code={`      - name: Fetch Baseline Policy from Main
        run: git show origin/main:agentdiff.toml > /tmp/baseline-agentdiff.toml

      - name: Gate Against Baseline with Governance Guard
        uses: lostmartian/agentdiff/.github/actions/agentdiff-check@main
        with:
          baseline: baselines/golden_run.json
          candidate: traces/pr_candidate.json
          baseline-config: /tmp/baseline-agentdiff.toml # Flags loosened thresholds
          pr: \${{ github.event.number }}
          github-token: \${{ secrets.GITHUB_TOKEN }}`}
            />
          </div>
        </div>
      </section>

      {/* 5. COMPLETE ACTION INPUTS SPECIFICATION */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 border-t border-(--border)">
        <Reveal>
          <div className="mb-12 max-w-3xl">
            <span className="text-xs font-mono uppercase tracking-[0.18em] text-(--faint) block mb-2">
              Action Parameters
            </span>
            <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-(--fg)">
              Inputs Specification
            </h2>
            <p className="mt-3 text-sm sm:text-base text-(--muted) leading-relaxed">
              All parameters supported by the <code className="font-mono text-xs text-(--fg)">agentdiff-check</code> action:
            </p>
          </div>
        </Reveal>

        <Reveal delay={100}>
          <div className="rounded-3xl border border-(--border) bg-(--surface) overflow-hidden shadow-xs">
            <div className="overflow-x-auto no-scrollbar">
              <table className="w-full text-left min-w-[700px]">
                <thead>
                  <tr className="border-b border-(--border) bg-(--surface-2)/80 text-xs font-mono text-(--faint) uppercase tracking-wider">
                    <th className="py-4 px-6 font-semibold text-(--fg) w-4/12">Parameter</th>
                    <th className="py-4 px-6 font-semibold text-(--fg) w-2/12">Requirement</th>
                    <th className="py-4 px-6 font-semibold text-(--fg) w-6/12">Description</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-(--border)/50 text-sm">
                  {ACTION_INPUTS.map((input) => (
                    <tr key={input.name} className="hover:bg-(--surface-2)/30 transition-colors">
                      <td className="py-4 px-6 font-mono text-xs font-semibold text-(--fg)">
                        {input.name}
                      </td>
                      <td className="py-4 px-6 font-mono text-xs">
                        {input.req ? (
                          <span className="text-emerald-500 font-semibold px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/25 text-[10.5px]">
                            REQUIRED
                          </span>
                        ) : (
                          <span className="text-(--faint) px-2 py-0.5 rounded bg-(--surface-2) border border-(--border) text-[10.5px]">
                            OPTIONAL
                          </span>
                        )}
                      </td>
                      <td className="py-4 px-6 text-sm text-(--muted) leading-relaxed">
                        {input.desc}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Reveal>
      </section>

      {/* 6. CTA */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center border-t border-(--border)">
        <Reveal>
          <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-(--fg) mb-3">
            Record. Diff. Gate. Ship.
          </h2>
          <p className="text-base text-(--muted) max-w-lg mx-auto mb-8 font-normal">
            Automate trajectory regression testing across your entire team in under five minutes.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4 text-sm font-semibold">
            <Link
              href="/quickstart"
              className="px-8 py-3.5 rounded-full bg-(--fg) text-(--bg) hover:opacity-90 transition-opacity"
            >
              Start the Quickstart →
            </Link>
            <Link
              href="/docs"
              className="px-8 py-3.5 rounded-full border border-(--border) text-(--fg) hover:bg-(--surface-2) transition-colors"
            >
              Explore Full CLI Docs
            </Link>
          </div>
        </Reveal>
      </section>
    </div>
  );
}
